### ISSUE TITLE
FATAL ERROR (shutting down): NUM_FOR_EDICT: bad pointer

### ISSUE THREAD

**Issue by stambeto2006** [Hun1eR/Print-Center-Fix#1]
My server is optimized to the latest versions and when I put this module 2.0.0 my server crashed.
![Capture](https://user-images.githubusercontent.com/5206809/148194916-435332e2-5599-43aa-a8ff-398106badf23.JPG)
dump file -  [hlds_3.11.0.771-dev-e6b44d2_crash_20220105_112402_1.zip](https://github.com/Hun1eR/Print-Center-Fix/files/7813739/hlds_3.11.0.771-dev-e6b44d2_crash_20220105_112402_1.zip)

OS: Windows 10
Print Center Fix 1.0.1 is not crash

**Comment by Hun1eR** [comment]
It looks like your antivirus (ESET Security) won't allow to patch the AMXX memory.
You can try to run the server with disabled antivirus or use the previous version of Print Center Fix.

**Comment by stambeto2006** [comment]
> It looks like your antivirus (ESET Security) won't allow to patch the AMXX memory.
> You can try to run the server with disabled antivirus or use the previous version of Print Center Fix.

With the previous version there are no problems and no errors, but with the latest one there is this problem!

**Comment by Hun1eR** [comment]
Because the new version uses the [Funchook](https://github.com/kubo/funchook) library, there are no other changes.
As I said, you can use the previous version. In terms of functionality, it is no different from the latest version.

**Comment by Hun1eR** [comment]
Because the new version uses the [Funchook](https://github.com/kubo/funchook) library, there are no other changes.
As I said, you can use the previous version. In terms of functionality, it is no different from the latest version.

**Comment by Hun1eR** [comment]
@stambeto2006 please try [new version](https://github.com/Hun1eR/Print-Center-Fix/releases/latest) and let me know if the bug still occurs for you.

**Comment by stambeto2006** [comment]
@Hun1eR Now it works well!
